[favicons]

cfg_schema = 1   # config's schema version no.

[favicons.proxy]

max_age = 604800             # 60 days / default: 7 days (604800 sec)

# [favicons.proxy.resolver_map]
#
# The available favicon resolvers are registered here.
#
# "duckduckgo" = "searx.favicons.resolvers.duckduckgo"
# "allesedv" = "searx.favicons.resolvers.allesedv"
# "google" = "searx.favicons.resolvers.google"
# "yandex" = "searx.favicons.resolvers.yandex"

[favicons.cache]

db_url = "/var/cache/searxng/faviconcache.db"  # default: "/tmp/faviconcache.db"
LIMIT_TOTAL_BYTES = 52428800                 # default: 50 MB
HOLD_TIME = 2592000                          # default: 30 days
BLOB_MAX_BYTES = 20480                         # default 20 KB
MAINTENANCE_MODE = "auto"                       # default: "auto"
MAINTENANCE_PERIOD = 6000                       # default: 1h

